# Generated by Django 3.2 on 2022-05-25 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=100)),
                ('estado_respuesta', models.CharField(max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now)),
                ('consulta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contacto.consulta')),
            ],
        ),
    ]
