# Generated by Django 3.2 on 2022-03-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'cuenta', 'verbose_name_plural': 'cuentas'},
        ),
    ]
