# Generated by Django 3.2 on 2022-06-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
    ]
