# Generated by Django 3.2 on 2022-03-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coleccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coleccion',
            options={'verbose_name': 'coleccion', 'verbose_name_plural': 'colecciones'},
        ),
    ]
