"""
Django settings for portal project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s)tr%6uzdu$nj@kb11d2bfiot@t_yg@@nb08)vg7=)61gf2spb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #'django.contrib.admin', # --> Remuevo para usar la plantilla de DJANGO-MATERIAL-ADMIN
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #De terceros
    'material', # Plantilla DJANGO-MATERIAL-ADMIN
    'material.admin', # Plantilla DJANGO-MATERIAL-ADMIN
    'captcha', # Aplicación captcha para los formularios de contacto

    #Propias
    'coleccion', #agrego la app para la gestion de colecciones del portal
    'cuentas', #agrego la app cuentas para la gestion de usuarios del portal
    'tienda', #agrego la app tienda para la gestion productos
    'carrito', #agrego la app tienda para la gestion de los carritos de compras
    'contacto', #agrego la app tienda para la gestion de los mensajes de contacto
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'], #establezco el directorio templates para que busque las plantillas
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'coleccion.context_processors.menu_links',
                'carrito.context_processors.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'portal.wsgi.application'

AUTH_USER_MODEL = 'cuentas.Account'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR /'static' #carpeta static del directorio raiz del proyecto
STATICFILES_DIRS = [
    'portal/static' #Directorio de recursos media 
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'

#Importo el manejo de alertas y errores para todo el proyecto
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR : 'danger',
}

#Configuro el host de correo para el envio de mails
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'libreriavirtual209@gmail.com'
EMAIL_HOST_PASSWORD = 'M1Libreri4Virtu4l!'
EMAIL_USE_TLS = True


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración del Portal de ADMIN
MATERIAL_ADMIN_SITE = {
    'HEADER':  ('Portal de Administración de la Libreria Virtual del INTA'),  # Admin site header
    'TITLE':  ('Libreria Virtual INTA'),  # Admin site title
    'FAVICON':  '/images/favicon.ico',  # Admin site favicon (path to static should be specified)
    #'MAIN_BG_COLOR':  'color',  # Admin site main color, css color should be specified
    #'MAIN_HOVER_COLOR':  'color',  # Admin site main hover color, css color should be specified
    #'PROFILE_PICTURE':  'path/to/image',  # Admin site profile picture (path to static should be specified)
    'PROFILE_BG':  '/images/perfil_bg.jpg',  # Admin site profile background (path to static should be specified)
    'LOGIN_LOGO':  '/images/logo_INTA.png',  # Admin site logo on login page (path to static should be specified)
    'LOGOUT_BG':  '/images/admin_bg.jpg',  # Admin site background on login/logout pages (path to static should be specified)
    'SHOW_THEMES':  False,  #  Show default admin themes button
    'TRAY_REVERSE': True,  # Hide object-tools and additional-submit-line by default
    'NAVBAR_REVERSE': True,  # Hide side navbar by default
    'SHOW_COUNTS': True, # Show instances counts for each modelz
    'APP_ICONS': {  # Set icons for applications(lowercase), includin 3rd party apps, {'application_name': 'material_icon_name', ...}
        'sites': 'send',
    },
    'MODEL_ICONS': {  # Set icons for models(lowercase), including 3rd party models, {'model_name': 'material_icon_name', ...}
        'site': 'contact_mail',
    }
}